apiVersion: chaos-mesh.org/v1alpha1
kind: GCPChaos
metadata:
  name: disk-loss-example
  namespace: chaos-testing
spec:
  action: disk-loss
  secretName: 'cloud-key-secret'
  project: 'your-project-id'
  zone: 'your-zone'
  instance: 'your-instance-name'
  deviceNames: ['disk-name']
  duration: '5m'
